### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589459352 for bb8824913917d6d527ca41aa97c676f894869833

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589459352

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589460354 for 61d80ba9995c9db0801ce445b0114865923e4921

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589460354

**Comment by CMCDragonkai** [comment]
Changes here should be incorporated into js-db. Except of course all the package builds. We don't need test load balancing there yet... so we can keep it simpler than what this demo repo shows.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589461181 for ccb57132fcf3aa2dc1adc5f72e933c3033e68938

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589461181

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589463396 for 570addbd8233b0035112adc90eeff5eaa483ccf3

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589463396

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589463567 for 9ff2a499f84aa9daeb7c580a82c1577c1251873e

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589463567

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589464085 for 0455dfbdb51548bf674835f9f9c203e145e4e4e2

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589464085

**Comment by CMCDragonkai** [comment]
Something strange here. Both on this repo and the TS demo lib, the second shared windows test job always fails. The test execution results in no output. @emmacasolin any ideas?

**Comment by CMCDragonkai** [comment]
I tried running `jest "--ci" "--coverage" "--shard=2/2" "--maxWorkers=50%"` directly on `matrix-win-1` and it worked fine. I am not able to replicate the error that's happening on CI/CD. Especially when there's no error message at all. There's no output after running that command, and it just goes into failure state.

**Comment by CMCDragonkai** [comment]
The only thing that could be an issue is that the compilation isn't working. That is after compiling the native addon and copying it into the second windows runner, something causes the native module to no longer execute properly.

This is because I can see a `GLOBAL SETUP` message, and the very next messages are supposed to come from the native addon directly:

```
keyValueString_size: 6
keyValueString_len: 6
```

But now I noticed that even on `matrix-win-1` the output looks strange:

```
size: 6eString_
keyValueString_len: 6
```

**Comment by CMCDragonkai** [comment]
Can't replicate it. Something is broken in gitlab...

**Comment by CMCDragonkai** [comment]
The only thing I can imagine is something about the native module breaking on the 2nd windows runner.

**Comment by CMCDragonkai** [comment]
Would be worth checking this out on js-db later to see if it also applies there.

But there's a problem, the 2nd windows runner is also failing in ts demo lib too and there's no native module there.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589518481 for 7a18cf671cafe4c314b564a37e63be8ae3462f3d

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589518481

**Comment by CMCDragonkai** [comment]
Latest job https://gitlab.com/MatrixAI/open-source/typescript-demo-lib/-/jobs/2730803683 shows that it fails without sharding and no native modules. Something must be breaking in jest and windows...

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589772008 for 7201d4e0b1e60301153b7dbaf2da3b9e73f86715

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589772008

**Comment by CMCDragonkai** [comment]
Actually the latest 2 runs have successful windows tests. No idea how that was fixed. Since this commit [7a18cf6](https://github.com/MatrixAI/TypeScript-Demo-Lib-Native/pull/45/commits/7a18cf671cafe4c314b564a37e63be8ae3462f3d), `build:windows` succeeded.

It's still failing on TypeScript-Demo-Lib, so I don't know why.

The only problem left for this CI/CD is the fact that the new `./prebuild.js` seems to have changed how `pkg.js` is bundling. It is bundling `build/Release/native.node` instead of bundling the `prebuilds` before.

This means the `integration:build` job is incorrectly calling something that isn't calling the proper prebuild script.

**Comment by CMCDragonkai** [comment]
I think this is because using `prebuildify`, it used to move the `build/Release/native.node` into the `prebuilds` location, but the current `prebuild.js` script only copies it. And we use `node-gyp-build` to find the right paths, and that's why it ends up bundling the `build/` location instead of the `prebuild` location.

We can change this by setting `PREBUILDS_ONLY=1` to ensure that it is bundling only prebuilds.

**Comment by CMCDragonkai** [comment]
Setting `PREBUILDS_ONLY` does mean that packages must only have prebuilds for it be found with `node-gyp-build`... it's not allowed to bundle with only just `builds/` directory. This should be sufficient since it's not likely people distribute native addon prebuilds in `node_modules` under the `build/` directory. Any other kind of native modules would need to be setup differently...

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 589791479 for abc6ade9a6a779716b0acaf6bebafe38a1a07513

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589791479

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 589791479 for abc6ade9a6a779716b0acaf6bebafe38a1a07513

https://gitlab.com/MatrixAI/open-source/typescript-demo-lib-native/-/pipelines/589791479

**Pull request merged**
